### ISSUE TITLE
Questions about perturbed area ratio

### ISSUE THREAD

**Issue by Zengyf-CVer** [VDIGPKU/RPAttack#1]
@VDIGPKU 
I read your paper, and I have some questions about the understanding of the perturbed area ratio in Figure 1 of the paper:
![00000000](https://user-images.githubusercontent.com/41098760/136411241-10f0f75a-a1b1-4d5a-8227-dacf16505117.PNG)

The calculation formula for perturbed area ratio is the area of the patch divided by the area of the image?
Or is the number of pixels in the patch divided by the total number of pixels in the image?

**Comment by Huaxingweichen** [comment]
I think both two are right. Could you tell me the difference between the two?

**Comment by Zengyf-CVer** [comment]
@Huaxingweichen 
From the calculation results, there is no difference between the two. A single pixel can be regarded as an area of 1×1.
But I have a question. As we all know, for all the pixels of the RGB image, the number of pixels is w×h×3. Assuming the number of disturbances is rn, then in your paper, calculate whether the disturbance ratio is rn/w·h·3 or rn/wh ?
In other words, does that 3 channel need to be considered?

**Comment by Huaxingweichen** [comment]
A good question. rn/wh is right. We do not care about the channel in the RGB image.

**Comment by Zengyf-CVer** [comment]
@Huaxingweichen 
Thank you very much.

**Comment by Huaxingweichen** [comment]
You are welcome.
