### ISSUE TITLE
Some questions about AS indicators

### ISSUE THREAD

**Issue by Zengyf-CVer** [VDIGPKU/RPAttack#2]
@Huaxingweichen 
Hello, I have some questions about the calculation of AS in formula 5 in your paper `4.1. Datasets and Implementation Details`:
![ksnip_20211010-150526](https://user-images.githubusercontent.com/41098760/136686257-7ccd8148-6afa-401f-81f0-b6d7fccf1eb7.png)

#### What does this "2" mean? Thanks.

**Comment by Huaxingweichen** [comment]
So, AS is the area score. The smaller the patch is, the higher the AS. If the area of the adversarial patches does not beyond the limitation, the minimum AS score is 1. The maximum AS is close but not up to 2.

**Comment by Zengyf-CVer** [comment]
@Huaxingweichen 
So the function of "2" is only to limit the range of AS to [1, 2]. If you use "1" instead of "2", then the range of AS becomes [0,1], then It is repeated with the "0" of `otherwise` below, so in order to avoid this duplication, the value range is changed to [1,2], which is the actual effect of this "2". Can this be understood?

**Comment by Huaxingweichen** [comment]
Actually, we follow the Alibaba contest setting. 
https://tianchi.aliyun.com/competition/entrance/531806/introduction

**Comment by Zengyf-CVer** [comment]
@Huaxingweichen 
I just took a look at the OS indicator:
![ksnip_20211010-155323](https://user-images.githubusercontent.com/41098760/136687467-7113d242-a6cf-4f58-ba07-56f122acce46.png)

I guess this "2" is like this:
First of all, the value range of the second term BS in OS is [0,1], so when OS becomes 0, in order to distinguish whether AS is 0 or BS is 0, so the value range of AS is increased to [1,2]. In this way, when OS is 0, you can know that BS is 0.
Thank you anyway.

**Comment by Huaxingweichen** [comment]
A reasonable explanation, thanks!
